src/ECommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from services.views import home
from django.conf import settings 
from django.conf.urls.static import static
from django_prometheus import exports as django_prometheus_exports

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('uses/',include('accounts.urls')),
    path('services/', include('services.urls')),
    path('mobiles/', include('mobile.urls')),
    path('inventaire/', include('inventaire.urls')),
    path('reporting/', include('reporting.urls')),
    path('metrics/', django_prometheus_exports.ExportToDjangoView, name='metrics'),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/inventaire/urls.py
from django.urls import path

from .views import ServerView , ServerDetailView , ServerCreateView , ServerUpdateView , ServerDeleteView, chart_form, generate_chart, previous_page, storagerack_chart, storagerack_form
from .views import export_servers_to_excel , import_servers_from_excel  
from .views import StorageRackView , StorageRackDetailView , StorageRackCreateView , StorageRackUpdateView , StorageRackDeleteView
from .views import export_storageracks_to_excel , import_storageracks_from_excel , index , indexserver , indexstoragerack
from .views import IncidentServerListView , IncidentServerCreateView , IncidentServerUpdateView , IncidentServerDeleteView , IncidentServerDetailView , indexincident
from .views import IncidentStorageRackCreateView , IncidentStorageRackUpdateView , IncidentStorageRackDeleteView , IncidentStorageRackDetailView , IncidentStorageRackListView
from .views import IncidentServerCreateView , IncidentServerUpdateView , IncidentServerDeleteView 
from .views import IncidentStorageRackCreateView , IncidentStorageRackUpdateView , IncidentStorageRackDeleteView 

app_name="inventaire"

urlpatterns = [
    #reverse path 
    path('previous/', previous_page, name='previous'),
    # list urls for server
    path ('', index, name='index'),
    path('server/', indexserver, name='gestionserver'),
    path('server/list', ServerView.as_view(), name='server'),
    path('server/<str:pk>', ServerDetailView.as_view(), name='server_detail'),
    path('server/create/', ServerCreateView.as_view(), name='server_create'),
    path('server/update/<str:pk>', ServerUpdateView.as_view(), name='server_update'),
    path('server/delete/<str:pk>', ServerDeleteView.as_view(), name='server_delete'),
    path('server/export/', export_servers_to_excel, name='exportserver'),
    path('server/import/', import_servers_from_excel, name='importserver'),
    path('server/stats/chart/', chart_form, name='chart_form'),
    path('server/stats/chart/generate/', generate_chart, name='generate_chart'),
    
    # list urls for storage rack
    path('storagerack/', indexstoragerack, name='gestionstoragerack'),
    path('storagerack/list', StorageRackView.as_view(), name='storagerack'),
    path('storagerack/<str:pk>', StorageRackDetailView.as_view(), name='storagerack_detail'),
    path('storagerack/create/', StorageRackCreateView.as_view(), name='storagerack_create'),
    path('storagerack/update/<str:pk>', StorageRackUpdateView.as_view(), name='storagerack_update'),
    path('storagerack/delete/<str:pk>', StorageRackDeleteView.as_view(), name='storagerack_delete'),
    path('storagerack/export/', export_storageracks_to_excel, name='export'),
    path('storagerack/import/', import_storageracks_from_excel, name='import'),
    path('storagerack/stats/chart', storagerack_form, name="storagerack_form"),
    path('storagerack/stats/chart/generate', storagerack_chart, name="storagerack_chart"), 


    path('incident/', indexincident, name='gestionincident'),

    # list urs for incident server
    path('incidentserver/list', IncidentServerListView.as_view(), name='incidentserver'),
    path('incidentserver/<str:pk>', IncidentServerDetailView.as_view(), name='incidentserver_detail'),
    path('incidentserver/create/', IncidentServerCreateView.as_view(), name='incidentserver_create'),
    path('incidentserver/update/<str:pk>', IncidentServerUpdateView.as_view(), name='incidentserver_update'),
    path('incidentserver/delete/<str:pk>', IncidentServerDeleteView.as_view(), name='incidentserver_delete'),
    
    # list urs for incident storagerack
    path('incidentstoragerack/list', IncidentStorageRackListView.as_view(), name='incidentstoragerack'),
    path('incidentstoragerack/<str:pk>', IncidentStorageRackDetailView.as_view(), name='incidentstoragerack_detail'),
    path('incidentstoragerack/create/', IncidentStorageRackCreateView.as_view(), name='incidentstoragerack_create'),
    path('incidentstoragerack/update/<str:pk>', IncidentStorageRackUpdateView.as_view(), name='incidentstoragerack_update'),
    path('incidentstoragerack/delete/<str:pk>', IncidentStorageRackDeleteView.as_view(), name='incidentstoragerack_delete'),
    #path('incidentstoragerack/<str:pk>', IncidentStorageRackDetailView.as_view(), name='incidentstoragerack_detail'),
    
]

src/mobile/urls.py
from django.urls import path

from .models import Category, Mobile, MobileImage
from django.forms import ModelForm
from mobile.views import CategoryListView , CategoryDetailView , CategoryCreateView , CategoryUpdateView , CategoryDeleteView , MobileCategoryListView
from mobile.views import MobileListView , MobileCreateView , MobileUpdateView , MobileDeleteView , MobileDetailView
from mobile.views import index
app_name = 'mobile'

urlpatterns = [
    path('', index, name='index'),
    # Category URLs
    path('category', CategoryListView.as_view(), name='home'),    
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # Mobile URLs
    path('mobile/list/', MobileListView.as_view(), name='mobile_list'),
    path('mobile/create/', MobileCreateView.as_view(), name='mobile_create'),
    path('mobile/update/<int:pk>/', MobileUpdateView.as_view(), name='mobile_update'),
    path('mobile/delete/<int:pk>/', MobileDeleteView.as_view(), name='mobile_delete'),
    path('mobile/<int:pk>/', MobileDetailView.as_view(), name='mobile_detail'),
    path('mobile/<int:pk>/category/', MobileCategoryListView.as_view(), name='mobile_category_list'),
]

src/inventaire/views.py
import os
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from matplotlib import pyplot as plt
from .models import  Server , StorageRack , IncidentServer , IncidentStorageRack
from django.urls import reverse_lazy
from django.http import HttpResponse
from openpyxl import load_workbook
import xlsxwriter 
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import ServerForm , StorageRackForm , IncidentServerForm , IncidentStorageRackForm
from django.shortcuts import render
from django.db.models import Count
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from  prometheus_client import Counter, MetricsHandler
from django.db.models import Count
from io import BytesIO
import base64
import matplotlib.pyplot as plt
from .models import Server
from .forms import ServerChartForm
import plotly.graph_objs as go


# Create server views here.
def index(request):
    return render(request, 'indexinven.html')

def indexserver(request):
    return render(request, 'server/indexserver.html')

def indexstoragerack(request):
    return render(request, 'storagerack/indexstoragerack.html')

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['SMC','Admin']).exists() or u.is_superuser), name='dispatch')
class ServerView(ListView):
    model = Server
    template_name = 'server/server_list.html'
    context_object_name = 'server_list'
    ordering = ['-acquisition_date']
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(serial_number__icontains=query) |
                Q(brand__icontains=query) |
                Q(site__icontains=query) |
                Q(project__icontains=query) |
                Q(operating_system__icontains=query)
            )
        return queryset
    
@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['SMC','Admin']).exists() or u.is_superuser), name='dispatch')
class ServerDetailView(DetailView):
    model = Server
    template_name = 'server/server_detail.html'
    context_object_name = 'server_detail'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['incidentserver_list'] = IncidentServer.objects.filter(server=self.object)
        return context
    
@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['SMC','Admin']).exists() or u.is_superuser), name='dispatch')
class ServerCreateView(CreateView):
    model = Server
    template_name = 'server/server_create.html'
    form_class = ServerForm
    success_url = reverse_lazy('inventaire:server')

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['SMC','Admin']).exists() or u.is_superuser), name='dispatch')
class ServerUpdateView(UpdateView):
    model = Server
    template_name = 'server/server_update.html'
    form_class = ServerForm
    success_url = reverse_lazy('inventaire:gestionserver')

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['SMC','Admin']).exists() or u.is_superuser), name='dispatch')
class ServerDeleteView(DeleteView):
    model = Server
    template_name = 'server/server_delete.html'
    context_object_name = 'server_detail'
    success_url = reverse_lazy('inventaire:server')

def export_servers_to_excel(request):
    # Retrieve the server data to export (you can modify this to suit your needs)
    servers = Server.objects.all()

    # Create a new Excel workbook and sheet
    response = HttpResponse(content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="servers.xlsx"'
    workbook = xlsxwriter.Workbook(response, {'in_memory': True})
    worksheet = workbook.add_worksheet()
    # Define the column headers
    headers = ['Serial number', 'Brand', 'Site', 'Support', 'Project', 'Acquisition date', 'MEP date', 'Operating system', 'RAM', 'Disk', 'CPU', 'Power']
    # Write the column headers to the first row of the sheet
    row = 0
    col = 0
    for header in headers:
        worksheet.write(row, col, header)
        col += 1
    # Write the server data to the sheet
    row = 1
    for server in servers:
        worksheet.write(row, 0, server.serial_number)
        worksheet.write(row, 1, server.brand)
        worksheet.write(row, 2, server.site)
        worksheet.write(row, 3, server.support)
        worksheet.write(row, 4, server.project)
        worksheet.write(row, 5, server.acquisition_date.strftime('%Y-%m-%d'))
        worksheet.write(row, 6, server.mep_date.strftime('%Y-%m-%d'))
        worksheet.write(row, 7, server.operating_system)
        worksheet.write(row, 8, server.ram)
        worksheet.write(row, 9, server.disk)
        worksheet.write(row, 10, server.cpu)
        worksheet.write(row, 11, server.power)
        row += 1

    # Close the workbook and return the response
    workbook.close()
    return response

def import_servers_from_excel(request):
    # Check if a file was uploaded
    if 'file' not in request.FILES:
        return render(request, 'server/import.html', {'error': 'No file selected'})

    # Get the uploaded file and load it into an openpyxl workbook object
    file = request.FILES['file']
    workbook = load_workbook(filename=file, read_only=True)

    # Get the active worksheet in the workbook
    worksheet = workbook.active

    # Loop over each row in the worksheet, skipping the header row
    for row in worksheet.iter_rows(min_row=2, values_only=True):
        # Convert datetime objects to strings
        acquisition_date_str = row[5]
        mep_date_str = row[6]

        # Create a new Server object using the data from the row
        server = Server(
            serial_number=row[0],
            brand=row[1],
            site=row[2],
            support=row[3],
            project=row[4],
            acquisition_date=acquisition_date_str,
            mep_date=mep_date_str,
            operating_system=row[7],
            ram=row[8],
            disk=row[9],
            cpu=row[10],
            power=row[11],
        )
        # Save the new Server object to the database
        server.save()
               

    # Redirect back to the import page with a success message
    return redirect('inventaire:server')

def previous_page(request):
    return redirect(request, "server/chary")

def chart_form(request):
    fields = ['serial_number', 'ip_address', 'brand', 'site', 'support', 
              'project', 'acquisition_date', 'mep_date', 'operating_system',
              'ram', 'disk', 'cpu', 'power', 'document']
    return render(request, 'server/chart_form.html', {'fields': fields})

def generate_chart(request):
    if request.method == 'POST':
        x_field = request.POST.get('x_field') # récupère la valeur de la clé 'x_field'
        # autres opérations pour générer le graphique
    else:
        # si la requête n'est pas POST, redirige l'utilisateur vers la page précédente
        return redirect(request.META.get('HTTP_REFERER'))   
    # Récupération des données
    x_field = request.POST['x_field']
    y_field = request.POST['y_field']
    servers = Server.objects.all()

    # Création des données pour le graphique
    x_data = [getattr(server, x_field) for server in servers]
    y_data = [getattr(server, y_field) for server in servers]
     
    # Création du graphique
    fig = go.Figure(data=go.Bar(x=x_data, y=y_data, marker_color='orangered'))
         
    # Personnalisation du graphique
    fig.update_layout(
        xaxis_title=x_field,
        yaxis_title=y_field,
        title=f"{x_field} par rappor à {y_field}"
    )

    # Rendu de la page
    chart = fig.to_html(full_html=False)

    return render(request, 'server/chart.html', {'chart': chart})
# Create storage rack views here.

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['SMC','Admin']).exists() or u.is_superuser), name='dispatch')
class StorageRackView(ListView):
    model = StorageRack
    template_name = 'storagerack/storage_rack_list.html'
    context_object_name = 'storage_rack_list'
    ordering = ['-acquisition_date']
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(serial_number__icontains=query) |
                Q(brand__icontains=query) |
                Q(site__icontains=query) |
                Q(project__icontains=query)
            )

        return queryset

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['SMC','Admin']).exists() or u.is_superuser), name='dispatch') 
class StorageRackDetailView(DetailView):
    model = StorageRack
    template_name = 'storagerack/storage_rack_detail.html'
    context_object_name = 'storage_rack_detail'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['incident_list'] = IncidentStorageRack.objects.filter(storage_rack=self.object)
        return context

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['SMC','Admin']).exists() or u.is_superuser), name='dispatch')
class StorageRackCreateView(CreateView):
    model = StorageRack
    template_name = 'storagerack/storage_rack_create.html'
    form_class = StorageRackForm
    success_url = reverse_lazy('inventaire:storagerack')

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['SMC','Admin']).exists() or u.is_superuser), name='dispatch')
class StorageRackUpdateView(UpdateView):
    model = StorageRack
    template_name = 'storagerack/storage_rack_update.html'
    form_class = StorageRackForm

src/inventaire/templates/incident/incident_server.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 2cm;">
    <h1 class="text-black mt-2">Liste des Incidents</h1>
    <hr>    
    <div class="container-fluid">
        <section>
            {% for incident in incident_server_list %}
            <div class="row ">
                <div class=" mb-4">
                  <div class="card">
                    <div class="card-body">
                      <div class="d-flex justify-content-between p-md-1">
                        <div class="d-flex flex-row">
                          <div class="align-self-center">
                            <i class="fas fa-pencil-alt fa-3x me-4" style="color: orangered;"></i>
                          </div>
                          <div>
                            
                            <h5>
                                Type d'incident : {{ incident.type_of_incident }}
                            </h5>
                            <h6 class="text-muted">Date de l'incident : {{ incident.date }}</h6>
                            <p class="mb-0"> {{ incident.description|truncatechars:100 }} </p>
                          </div>
                        </div>
                        <div class="align-self-center">
                          <h4 class="h1 mb-0 mt-2">
                            <a href="{% url 'inventaire:incidentserver_detail' incident.id %}"><i class="far fa-eye fa-xs" style="color: orangered;"></i></a>
                            <a href="{% url 'inventaire:incidentserver_update' incident.id %}"><i class="far fa-edit fa-xs" style="color: orangered;"></i></a>
                            <a href="{% url 'inventaire:incidentserver_delete' incident.id %}"><i class="fas fa-trash fa-xs" style="color: orangered;"></i></a>
                          </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
            {% endfor %}
        </section>
      </div>
    
        
    
</div>
{% endblock %}

src/inventaire/templates/incident/incident_server_delete.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 2cm;">
    <h1 style="color: orangered;">Supprimer un incident</h1>
        <form method="post">
        {% csrf_token %}
        <p class="text-black mx-2" >Êtes-vous sûr de vouloir supprimer  {{ incident_server_detail.id }} ?</p>
        <button type="submit" class="btn btn-black">Oui</button>
        <a href="{% url 'inventaire:index' %}" class="btn btn-black">Non</a>
    </form>
</div>
{% endblock %}

src/inventaire/templates/incident/incident_server_detail.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 2cm;">
    <h1 class="font-bold" style="color:black;">Incident Server Detail</h1>
    <hr>
    <div class="container-fluid">
        <section>
            <div class="row ">
                <div class=" mb-4">
                  <div class="card">
                    <div class="card-body">
                      <div class="d-flex justify-content-between p-md-1">
                          <div>
                            <h3 class="text-black text-blod">
                                L'incident est survenu sur le serveur : {{ incident_server_detail.server}}
                            </h3>
                            Type d'incident : {{ incident_server_detail.type_of_incident }}

                            <h6 >Date de l'incident : {{ incident_server_detail.date | date:"d-m-Y" }}</h6>
                            <h5 class="text-black text-blod">
                                Description de l'incident :
                            </h5>
                            <p>
                                {{ incident_server_detail.description }}
                            </p>
                            <h5 class="text-black">
                                Solution de l'incident :
                            </h5>
                            <p>
                                {{ incident_server_detail.solution }}
                            </p>
                          </div>
                        </div>
                        
                      </div>
                      <div class="align-self-center ">
                        <h4 class="h1 mb-0 mt-2">
                        <a href="{% url 'inventaire:incidentserver_update' incident_server_detail.id %}" class="btn"><i class="fas fa-pen-to-square fa-2x" style="color: orangered;"></i></a>
                        <a href="{% url 'inventaire:incidentserver_delete' incident_server_detail.id %}" class="btn"><i class="fas fa-trash fa-2x" onclick="return confirm('Are you sure you want to delete this item?');"style="color: orangered;"></i></a>
                        <a href="{% url 'inventaire:incidentserver'%}" class="btn"><i class="fas fa-rotate-left fa-2x" style="color: orangered;"></i></a>
                      </h4>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        </section>
      </div>
    
        
    
</div>
{% endblock %}

src/inventaire/templates/incident/incident_storagerack.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 2cm;">
    <h1 class="text-black mt-2">Liste des Incidents</h1>
    <hr>    
    <div class="container-fluid">
        <section>
            {% for incident in incident_storagerack_list %}
            <div class="row ">
                <div class=" mb-4">
                  <div class="card">
                    <div class="card-body">
                      <div class="d-flex justify-content-between p-md-1">
                        <div class="d-flex flex-row">
                          <div class="align-self-center">
                            <i class="fas fa-pencil-alt fa-3x me-4" style="color: orangered;"></i>
                          </div>
                          <div>
                            
                            <h5>
                                Type d'incident : {{ incident.type_of_incident }}
                            </h5>
                            <h6 class="text-muted">Date de l'incident : {{ incident.date }}</h6>
                            <p class="mb-0"> {{ incident.description|truncatechars:100 }} </p>
                          </div>
                        </div>
                        <div class="align-self-center">
                          <h4 class="h1 mb-0 mt-2">
                            <a href="{% url 'inventaire:incidentstoragerack_detail' incident.id %}"><i class="far fa-eye fa-xs" style="color: orangered;"></i></a>
                            <a href="{% url 'inventaire:incidentstoragerack_update' incident.id %}"><i class="far fa-edit fa-xs" style="color: orangered;"></i></a>
                            <a href="{% url 'inventaire:incidentstoragerack_delete' incident.id %}"><i class="fas fa-trash fa-xs" style="color: orangered;"></i></a>
                          </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
            {% endfor %}
        </section>
      </div>
    
        
    
</div>
{% endblock %}

src/inventaire/templates/incident/incident_storagerack_delete.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 2cm;">
    <h1 style="color: orangered;">Supprimer un incident</h1>
        <form method="post">
        {% csrf_token %}
        <p class="text-black mx-2" >Êtes-vous sûr de vouloir supprimer  {{ incident_storagerack_detail.type_of_incident }} ?</p>
        <button type="submit" class="btn btn-black">Oui</button>
        <a href="{% url 'inventaire:index' %}" class="btn btn-black">Non</a>
    </form>
</div>
{% endblock %}

src/inventaire/templates/incident/incident_storagerack_detail.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 2cm;">
    <h1 class="font-bold" style="color:black;">Incident Server Detail</h1>
    <hr>
    <div class="container-fluid">
        <section>
            <div class="row ">
                <div class=" mb-4">
                  <div class="card">
                    <div class="card-body">
                      <div class="d-flex justify-content-between p-md-1">
                          <div>
                            <h3 class="text-black text-blod">
                                L'incident est survenu sur le serveur : {{ incident_storagerack_detail.storage_rack }}
                            </h3>
                            Type d'incident : {{ incident_storagerack_detail.type_of_incident }}

                            <h6 >Date de l'incident : {{ incident_storagerack_detail.date | date:"d-m-Y" }}</h6>
                            <h5 class="text-black text-blod">
                                Description de l'incident :
                            </h5>
                            <p>
                                {{ incident_storagerack_detail.description }}
                            </p>
                            <h5 class="text-black">
                                Solution de l'incident :
                            </h5>
                            <p>
                                {{ incident_storagerack_detail.solution }}
                            </p>
                          </div>
                        </div>
                        
                      </div>
                      <div class="align-self-center ">
                        <h4 class="h1 mb-0 mt-2">
                        <a href="{% url 'inventaire:incidentstoragerack_update' incident_storagerack_detail.id %}" class="btn"><i class="fas fa-pen-to-square fa-2x" style="color: orangered;"></i></a>
                        <a href="{% url 'inventaire:incidentstoragerack_delete' incident_storagerack_detail.id %}" class="btn"><i class="fas fa-trash fa-2x" style="color: orangered;"></i></a>
                        <a href="{% url 'inventaire:incidentstoragerack'%}" class="btn"><i class="fas fa-rotate-left fa-2x" style="color: orangered;"></i></a>
                      </h4>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        </section>
      </div>
    
        
    
</div>
{% endblock %}

src/inventaire/templates/incident/index.html
{% extends 'base.html' %}

{% block content  %}

<style>

</style>
<div class="row" style="margin-top: 2cm;">
    <div class="col-md-12 mt-5">
      <h1 class=" font-bold" style="color: black;">Gestion des incidents</h1>
      <hr>
      <div class="container-fluid">
        <section>
          <div class="row">
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card">
                <div class="card-body">
                  <a href="{% url 'inventaire:incidentserver_create' %}">
                  <div class="d-flex justify-content-between p-md-1">
                    <div class="d-flex flex-row">
                      <div class="align-self-center">
                        <i class="fas fa-circle-plus fa-2x me-4" style="color: orangered;"></i>
                      </div>
                      <div>
                        <h6 class=" font-semibold mb-0 mt-2" style="color: black;" >Ajouter un incident Pour un serveur</h6>
                      </div>
                    </div>
                  </div>
                  </a>
                </div>
              </div>
            </div>
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card">
                <div class="card-body">
                  <a href="{% url 'inventaire:incidentstoragerack_create' %}">
                  <div class="d-flex justify-content-between p-md-1">
                    <div class="d-flex flex-row">
                      <div class="align-self-center">
                        <i class="fas fa-circle-plus fa-2x me-4" style="color: orangered;"></i>
                      </div>
                      <div>
                        <h6 class=" font-semibold mb-0 mt-2" style="color: black;" >Ajouter un incident Pour un baie de stockage</h6>
                      </div>
                    </div>
                  </div>
                  </a>
                </div>
              </div>
            </div>
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card">
                <div class="card-body">
                  <a href="{% url 'inventaire:incidentserver' %}">
                  <div class="d-flex justify-content-between p-md-1">
                    <div class="d-flex flex-row">
                      <div class="align-self-center">
                        <i class="fas fa-table-list fa-2x me-4"style="color: orangered;"></i>
                      </div>
                      <div>
                        <h6 class=" font-semibold mb-0 mt-2"style="color: black;">Liste des incidents des serveurs</h6>
                      </div>
                    </div>
                  </div>
                  </a>
                </div>
              </div>
            </div>
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card">
                <div class="card-body">
                  <a href="{% url 'inventaire:incidentstoragerack' %}">
                  <div class="d-flex justify-content-between p-md-1">
                    <div class="d-flex flex-row">
                      <div class="align-self-center">
                        <i class="fas fa-table-list fa-2x me-4"style="color: orangered;"></i>
                      </div>
                      <div>
                        <h6 class=" font-semibold mb-0 mt-2"style="color: black;">Liste des incidents des baies de stockage</h6>
                      </div>
                    </div>
                  </div>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
{% endblock %}