src/ECommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from services.views import home
from django.conf import settings 
from django.conf.urls.static import static
from django_prometheus import exports as django_prometheus_exports

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('uses/',include('accounts.urls')),
    path('services/', include('services.urls')),
    path('mobiles/', include('mobile.urls')),
    path('inventaire/', include('inventaire.urls')),
    path('reporting/', include('reporting.urls')),
    path('metrics/', django_prometheus_exports.ExportToDjangoView, name='metrics'),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path

from accounts.views import  index , MyLoginView  , update , profile , CustomerPasswordChangeView , CustomerListView , detail , CustomerRegistrationView , delete
from django.contrib.auth.views import LogoutView 
from .views import CustomerPasswordChangeView , login_log , MyLogoutView , parameter
app_name="accounts"

urlpatterns = [
    path('',index , name="index"),
    path('parameter/',parameter , name="parameter"),
    path('login/',MyLoginView.as_view() ,name="login"),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('register/',CustomerRegistrationView.as_view() ,name="register"),
    path('profile/',profile ,name="profile"),
    path('detail/<int:pk>/',detail ,name="detail"),
    path('list/',CustomerListView.as_view() ,name="list"),
    path('update/<int:pk>/',update ,name="update"),
    path('password/<int:pk>/',CustomerPasswordChangeView.as_view() ,name="password"),
    path('delete/<int:pk>/',delete ,name="delete"),
    path('login_log/<int:pk>/',login_log ,name="login_log"),
]

src/inventaire/urls.py
from django.urls import path

from .views import ServerView , ServerDetailView , ServerCreateView , ServerUpdateView , ServerDeleteView, chart_form, generate_chart, previous_page, storagerack_chart, storagerack_form
from .views import export_servers_to_excel , import_servers_from_excel  
from .views import StorageRackView , StorageRackDetailView , StorageRackCreateView , StorageRackUpdateView , StorageRackDeleteView
from .views import export_storageracks_to_excel , import_storageracks_from_excel , index , indexserver , indexstoragerack
from .views import IncidentServerListView , IncidentServerCreateView , IncidentServerUpdateView , IncidentServerDeleteView , IncidentServerDetailView , indexincident
from .views import IncidentStorageRackCreateView , IncidentStorageRackUpdateView , IncidentStorageRackDeleteView , IncidentStorageRackDetailView , IncidentStorageRackListView
from .views import IncidentServerCreateView , IncidentServerUpdateView , IncidentServerDeleteView 
from .views import IncidentStorageRackCreateView , IncidentStorageRackUpdateView , IncidentStorageRackDeleteView 

app_name="inventaire"

urlpatterns = [
    #reverse path 
    path('previous/', previous_page, name='previous'),
    # list urls for server
    path ('', index, name='index'),
    path('server/', indexserver, name='gestionserver'),
    path('server/list', ServerView.as_view(), name='server'),
    path('server/<str:pk>', ServerDetailView.as_view(), name='server_detail'),
    path('server/create/', ServerCreateView.as_view(), name='server_create'),
    path('server/update/<str:pk>', ServerUpdateView.as_view(), name='server_update'),
    path('server/delete/<str:pk>', ServerDeleteView.as_view(), name='server_delete'),
    path('server/export/', export_servers_to_excel, name='exportserver'),
    path('server/import/', import_servers_from_excel, name='importserver'),
    path('server/stats/chart/', chart_form, name='chart_form'),
    path('server/stats/chart/generate/', generate_chart, name='generate_chart'),
    
    # list urls for storage rack
    path('storagerack/', indexstoragerack, name='gestionstoragerack'),
    path('storagerack/list', StorageRackView.as_view(), name='storagerack'),
    path('storagerack/<str:pk>', StorageRackDetailView.as_view(), name='storagerack_detail'),
    path('storagerack/create/', StorageRackCreateView.as_view(), name='storagerack_create'),
    path('storagerack/update/<str:pk>', StorageRackUpdateView.as_view(), name='storagerack_update'),
    path('storagerack/delete/<str:pk>', StorageRackDeleteView.as_view(), name='storagerack_delete'),
    path('storagerack/export/', export_storageracks_to_excel, name='export'),
    path('storagerack/import/', import_storageracks_from_excel, name='import'),
    path('storagerack/stats/chart', storagerack_form, name="storagerack_form"),
    path('storagerack/stats/chart/generate', storagerack_chart, name="storagerack_chart"), 


    path('incident/', indexincident, name='gestionincident'),

    # list urs for incident server
    path('incidentserver/list', IncidentServerListView.as_view(), name='incidentserver'),
    path('incidentserver/<str:pk>', IncidentServerDetailView.as_view(), name='incidentserver_detail'),
    path('incidentserver/create/', IncidentServerCreateView.as_view(), name='incidentserver_create'),
    path('incidentserver/update/<str:pk>', IncidentServerUpdateView.as_view(), name='incidentserver_update'),
    path('incidentserver/delete/<str:pk>', IncidentServerDeleteView.as_view(), name='incidentserver_delete'),
    
    # list urs for incident storagerack
    path('incidentstoragerack/list', IncidentStorageRackListView.as_view(), name='incidentstoragerack'),
    path('incidentstoragerack/<str:pk>', IncidentStorageRackDetailView.as_view(), name='incidentstoragerack_detail'),
    path('incidentstoragerack/create/', IncidentStorageRackCreateView.as_view(), name='incidentstoragerack_create'),
    path('incidentstoragerack/update/<str:pk>', IncidentStorageRackUpdateView.as_view(), name='incidentstoragerack_update'),
    path('incidentstoragerack/delete/<str:pk>', IncidentStorageRackDeleteView.as_view(), name='incidentstoragerack_delete'),
    #path('incidentstoragerack/<str:pk>', IncidentStorageRackDetailView.as_view(), name='incidentstoragerack_detail'),
    
]

src/mobile/urls.py
from django.urls import path

from .models import Category, Mobile, MobileImage
from django.forms import ModelForm
from mobile.views import CategoryListView , CategoryDetailView , CategoryCreateView , CategoryUpdateView , CategoryDeleteView , MobileCategoryListView
from mobile.views import MobileListView , MobileCreateView , MobileUpdateView , MobileDeleteView , MobileDetailView
from mobile.views import index
app_name = 'mobile'

urlpatterns = [
    path('', index, name='index'),
    # Category URLs
    path('category', CategoryListView.as_view(), name='home'),    
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # Mobile URLs
    path('mobile/list/', MobileListView.as_view(), name='mobile_list'),
    path('mobile/create/', MobileCreateView.as_view(), name='mobile_create'),
    path('mobile/update/<int:pk>/', MobileUpdateView.as_view(), name='mobile_update'),
    path('mobile/delete/<int:pk>/', MobileDeleteView.as_view(), name='mobile_delete'),
    path('mobile/<int:pk>/', MobileDetailView.as_view(), name='mobile_detail'),
    path('mobile/<int:pk>/category/', MobileCategoryListView.as_view(), name='mobile_category_list'),
]

src/reporting/urls.py
from django.urls import path
from .import views
from .views import ServerGraphPDFView , indexreport

app_name = 'reporting'

urlpatterns = [
    path('inventory-report/', ServerGraphPDFView.as_view(), name='inventory_report'),
    path('email-report/', views.email_report, name='email_report'),
    path('index/', indexreport, name='index'),
]

src/services/urls.py
from django.urls import path
from services.views import HomeView  , ServiceCreateView , ServiceUpdateView , ServiceDeleteView , ServiceDetailView , index
from services.views import CategoryServiceListView , CategoryServiceDetailView , CategoryServiceCreateView , CategoryServiceUpdateView , CategoryServiceDeleteView , ServicesCategoryListView
app_name="services"

urlpatterns = [
    path('', index, name='index'),
    path('list/', HomeView.as_view(), name='home'),
    path('create/', ServiceCreateView.as_view() , name="create"),
    path('update/<int:pk>', ServiceUpdateView.as_view() , name="upated"),
    path('delete/<int:pk>', ServiceDeleteView.as_view() , name="delete"),
    path('detail/<int:pk>', ServiceDetailView.as_view() , name="detail"),
    path('category/', CategoryServiceListView.as_view() , name="category"),
    path('category/<int:pk>', CategoryServiceDetailView.as_view() , name="category_detail"),
    path('category/create/', CategoryServiceCreateView.as_view() , name="category_create"),
    path('category/update/<int:pk>', CategoryServiceUpdateView.as_view() , name="category_update"),
    path('category/delete/<int:pk>', CategoryServiceDeleteView.as_view() , name="category_delete"),
    path('category/<int:pk>/services', ServicesCategoryListView.as_view() , name="category_services"),


]

src/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Orange-TN</title>
  {% block title %}{% endblock title %}
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.css"
  integrity="sha512-baC52JnHsCBvOpxWd8ze7wuIgqgzFmOdpLlWntf8GtrwRQlOQrGZtMcnZQZZN76tUs0b/+bbvEiLcB8Cz/VDug=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
  integrity="sha512-7VzpOX6Y9h7V5E6YZz0LpTpTkqC+dBz6UZI6UZ+6kR9XQOv5b5HK5xaIh7Bku3q3u0nKMgNzZevK7NfLhpy9+w=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.js"
  integrity="sha512-vvoF3Ej8oYNpJdt3qON3M1Df50WxMchPAPoPOI2+DR6nAGz6UZ9hqsn88UPRcfedOW5P5V5UNyB+yq3Srg1xLg=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css" rel="stylesheet" />
<link rel="shortcut icon" href="{% static 'img/orangelogo.png'%}" type="image/x-icon" width="100px" height="150px">

<body>
    {% load static %}
    <style>
      .nav-item.me-3:hover {
        color: rgb(255, 255, 255) !important;
        border-radius: 10px;
      }
    
      .nav-link:hover {
        color: orangered !important;
      }
    
      .dropdown-item:hover {
        color: rgb(255, 255, 255) !important;
        background-color: orangered !important;
      }
    </style>
    <!-- Navbar -->
    <div class="navbar navbar-light navbar-expand-md navigation-clean" style="background: rgb(0, 0, 0);">
      <div class="container-fluid">
        <!-- Icons -->
        <ul class="navbar-nav d-flex flex-row me-1">
          <li class="nav-item me-3 me-lg-0">
            <a class="nav-link mx-1 text-white" href="https://www.instagram.com/orange_tunisie/"><i
                class="fab fa-instagram fa-lg"></i></a>
          </li>
          <li class="nav-item me-3 me-lg-0">
            <a class="nav-link mx-1 text-white" href="https://www.facebook.com/orange.tn"><i
                class="fab fa-facebook fa-lg"></i></a>
          </li>
          <li class="nav-item me-3 me-lg-0">
            <a class="nav-link mx-1 text-white" href="https://twitter.com/orange"><i class="fab fa-twitter fa-lg"></i></a>
          </li>
          <li class="nav-item me-3 me-lg-0">
            <a class="nav-link mx-1 text-white" href="https://www.linkedin.com/company/orange/"><i
                class="fab fa-linkedin fa-lg"></i></a>
          </li>
        </ul>
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'home' %}">
          <img src="{% static 'img/orangelogo.png'%}" style="width: 65px; height: 65px;" height="15" alt="MDB Logo"
            loading="lazy" />
        </a>
        <!-- Search form -->
        <div class="input-group"
          style="background-color: rgb(255, 255, 255) !important; border-radius: 10px ; width: 300px;">
          <div id="navbar-search-autocomplete" class="form-outline">
            <input type="search" id="form1" class="form-control" />
          </div>
          <button type="button" class="btn btn-primary"
            style="border-radius: 0px 10px 10px 0px; background-color: orangered;">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </div>
    <!-- Navbar -->
  {% block content %}
  {% endblock content %}



  <!-- MDB -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.js"></script>
  <script src="{% static 'js/jquery.min.js'%}"></script>
  <script src="{% static 'js/popper.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/main.js'%}"></script>
</body>

</html>

src/templates/nav.html
{% load static %}
<style>
  .nav-item.me-3:hover {
    color: rgb(255, 255, 255) !important;
    border-radius: 10px;
  }

  .nav-link:hover {
    color: orangered !important;
  }

  .dropdown-item:hover {
    color: rgb(255, 255, 255) !important;
    background-color: orangered !important;
  }
</style>
<!-- Navbar -->
<div class="navbar navbar-light navbar-expand-md navigation-clean" style="background: rgb(0, 0, 0);">
  <div class="container-fluid">
    <!-- Icons -->
    <ul class="navbar-nav d-flex flex-row me-5">
      <li class="nav-item me-5 me-lg-5">
        <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'home' %}">
          <img src="{% static 'img/orangelogo.png'%}" style="width: 65px; height: 65px;" height="15" alt="MDB Logo"
            loading="lazy" />
        </a>
      </li>
    </ul>
    <!-- Navbar brand -->
    
    <!-- Search form -->
    <div class="input-group"
      style="background-color: rgb(255, 255, 255) !important; border-radius: 10px ; width: 300px;">
      <div id="navbar-search-autocomplete" class="form-outline">
        <input type="search" id="form1" class="form-control" />
      </div>
      <button type="button" class="btn btn-primary"
        style="border-radius: 0px 10px 10px 0px; background-color: orangered;">
        <i class="fas fa-search"></i>
      </button>
    </div>
  </div>
</div>
<!-- Navbar -->
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background: rgb(233, 232, 232);">
  <!-- Container wrapper -->
  <div class="container-fluid" style="background: rgb(255, 255, 255);">
    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left links -->
      <ul class="navbar-nav me-auto  mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-dark" style="font-size: 20px;" href="{% url 'home' %}">Accueil</a>
        </li>
        {% if user.is_superuser %}
        <li class="nav-item dropdown">
          <a class="nav-link text-dark" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown-menu" aria-expanded="false">
            Utilisateurs
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'accounts:list' %}">Liste des utilisateurs</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:register' %}">Ajouter un utilisateur</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link text-dark" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Inventaire
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'inventaire:server' %}">Liste des serveurs</a></li>
            <li><a class="dropdown-item" href="{% url 'inventaire:server_create' %}">Ajouter un serveur</a></li>
            <li><a class="dropdown-item" href="{% url 'inventaire:storagerack' %}">Liste des bai de stockage</a></li>
            <li><a class="dropdown-item" href="{% url 'inventaire:storagerack_create' %}">Ajouter un serveur</a></li>
            <li><a class="dropdown-item" href="{% url 'reporting:inventory_report' %}">Telecharger le rapport </a></li>
            <li><a class="dropdown-item" href="{% url 'reporting:email_report' %}">Envoyer le rapport par mail </a></li>
          </ul>
        </li>   
                   
        <li class="nav-item dropdown">
          <a class="nav-link text-dark" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown-menu" aria-expanded="false">
            Offres Mobiles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'services:home' %}">Liste des Offres Mobiles</a></li>
            <li><a class="dropdown-item" href="{% url 'services:create' %}">Ajouter une offre mobile</a></li>
            <li><a class="dropdown-item" href="{% url 'services:category' %}">Liste des catégories</a></li>
            <li><a class="dropdown-item" href="{% url 'services:category_create' %}">Ajouter une catégorie</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link text-dark" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown-menu" aria-expanded="false">
            Smartphones
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'mobile:mobile_list' %}">Liste des Smartphones </a></li>
            <li><a class="dropdown-item" href="{% url 'mobile:mobile_create' %}">Ajouter un Smartphone </a></li>
            <li><a class="dropdown-item" href="{% url 'mobile:home' %}">Liste des Categories </a></li>
            <li><a class="dropdown-item" href="{% url 'mobile:category_create' %}">Ajouter un Categorie </a></li>
          </ul>
        </li>
<<<<<<< HEAD
        <li class="nav-item dropdown">
          <a class="nav-link text-dark" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown-menu" aria-expanded="false">
            Rapport
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'reporting:inventory_report' %}">Telecharger le rapport </a></li>
            <li><a class="dropdown-item" href="{% url 'reporting:email_report' %}">Envoyer le rapport par mail </a></li>
          </ul>
        </li>
=======
>>>>>>> 9ba9baa5b0ac145e274af481b3eae0c74f8c256f
        {% elif user.groups.all.0.name == 'SMC' %}
        <li class="nav-item mt-1 text-dark"><a class="nav-link" href="{% url 'services:home' %}">Les Offres Mobiles</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link text-dark" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown-menu" aria-expanded="false">
            Smartphones
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'mobile:mobile_list' %}">Liste des Smartphones </a></li>
            <li><a class="dropdown-item" href="{% url 'mobile:mobile_create' %}">Ajouter un Smartphone </a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link text-dark" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown-menu" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'mobile:home' %}">Liste des Categories </a></li>
            <li><a class="dropdown-item" href="{% url 'mobile:category_create' %}">Ajouter un Categorie </a></li>
          </ul>
        </li>
               
        {% elif user.groups.all.0.name == 'IT' %}
        <li class="nav-item dropdown">
          <a class="nav-link text-dark" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown-menu" aria-expanded="false">
            Offres Mobiles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'services:home' %}">Liste des Offres </a></li>
            <li><a class="dropdown-item" href="{% url 'services:create' %}">Ajouter une Offre </a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link text-dark" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown-menu" aria-expanded="false">
            Smartphones
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'mobile:mobile_list' %}">Liste des Smartphones </a></li>
            <li><a class="dropdown-item" href="{% url 'mobile:mobile_create' %}">Ajouter un Smartphone </a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link text-dark" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown-menu" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'mobile:home' %}">Liste des Categories </a></li>
            <li><a class="dropdown-item" href="{% url 'mobile:category_create' %}">Ajouter un Categorie </a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item mt-1"><a class="nav-link text-dark" href="{% url 'services:home' %}">Les Offres Mobiles</a>
        </li>
        <li class="nav-item mt-1"><a class="nav-link text-dark" href="{% url 'mobile:mobile_list' %}">Les Smartphones
          </a></li>
        {% endif %}
      </ul>
      
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
    <!-- Right elements -->
    <div class="d-flex align-items-center" style="margin-right: 8% !important;">
      <ul class="navbar-nav me-auto  mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link" style="font-size: 20px;" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown-menu" aria-expanded="false">
            {{ user.username }}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">{{ user.username }}</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:update' user.id %}">Modifier le profil</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:password' user.id %}">Confidentialité</a></li>
            <hr>
            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Se Deconnecter</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item text-dark" style="font-size: 20px;"><a href="{% url 'accounts:login' %}" class="nav-link">Se
            Connecter</a></li>
        {% endif %}
      </ul>
      <!-- Icon -->
    </div>
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

src/templates/nav1.html
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

<!-- Right navbar links -->
<ul class="navbar-nav ml-auto">
    <!-- Navbar Search -->
    <li class="nav-item">
      <a class="nav-link" data-widget="navbar-search" href="#" role="button">
        <i class="fas fa-search"></i>
      </a>
      <div class="navbar-search-block">
        <form class="form-inline">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
              <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>
</ul>