src/ECommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from services.views import home
from django.conf import settings 
from django.conf.urls.static import static
from django_prometheus import exports as django_prometheus_exports

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('uses/',include('accounts.urls')),
    path('services/', include('services.urls')),
    path('mobiles/', include('mobile.urls')),
    path('inventaire/', include('inventaire.urls')),
    path('reporting/', include('reporting.urls')),
    path('metrics/', django_prometheus_exports.ExportToDjangoView, name='metrics'),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/mobile/urls.py
from django.urls import path

from .models import Category, Mobile, MobileImage
from django.forms import ModelForm
from mobile.views import CategoryListView , CategoryDetailView , CategoryCreateView , CategoryUpdateView , CategoryDeleteView , MobileCategoryListView
from mobile.views import MobileListView , MobileCreateView , MobileUpdateView , MobileDeleteView , MobileDetailView
from mobile.views import index
app_name = 'mobile'

urlpatterns = [
    path('', index, name='index'),
    # Category URLs
    path('category', CategoryListView.as_view(), name='home'),    
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # Mobile URLs
    path('mobile/list/', MobileListView.as_view(), name='mobile_list'),
    path('mobile/create/', MobileCreateView.as_view(), name='mobile_create'),
    path('mobile/update/<int:pk>/', MobileUpdateView.as_view(), name='mobile_update'),
    path('mobile/delete/<int:pk>/', MobileDeleteView.as_view(), name='mobile_delete'),
    path('mobile/<int:pk>/', MobileDetailView.as_view(), name='mobile_detail'),
    path('mobile/<int:pk>/category/', MobileCategoryListView.as_view(), name='mobile_category_list'),
]

src/mobile/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    mobiles = models.ManyToManyField('Mobile', related_name='categories')

    def __str__(self):
        return self.title


class Mobile(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    rom = models.IntegerField(default=0)
    ram = models.IntegerField(default=0)
    cpu = models.CharField(max_length=100 , null=True, blank=True)
    taille = models.FloatField(default=0)
    resolution = models.CharField(max_length=100, null=True, blank=True)
    profndeur = models.FloatField(default=0)
    Rafra = models.FloatField(default=0)
    system = models.CharField(max_length=100, null=True, blank=True)
    battery = models.IntegerField(default=0)
    type = models.CharField(max_length=100, null=True, blank=True)
    camera_front = models.IntegerField(default=0)
    camera_rear = models.IntegerField(default=0)
    video = models.CharField(max_length=100, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
class MobileImage(models.Model):
    mobile = models.ForeignKey(Mobile, on_delete=models.CASCADE , related_name='images', null=True)
    image = models.ImageField(upload_to='mobile_images/')

    def __str__(self):
        return self.mobile.title

src/mobile/forms.py
from django import forms

from .models import Category, Mobile, MobileImage

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title', 'description')
        labels = {
            'title': 'Titre',
            'description': 'Description',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

class MobileForm(forms.ModelForm):
    class Meta:
        model = Mobile
        fields = ('title', 'price','rom','ram','cpu','taille','resolution','profndeur','Rafra','system','battery','type','camera_front','camera_rear','video','category')
        labels = {
            'title': 'Titre du Mobile',
            'price': 'Prix',
            'rom': 'Stockage interne',
            'ram': 'Mémoire vive',
            'cpu': 'Processeur',
            'taille': 'Taille de l\'ecran',
            'resolution': 'Resolution de l\'ecran',
            'profndeur': 'Profondeur de Couleur',
            'Rafra': 'Rafraichissement de l\'ecran',
            'system': 'Système d\'exploitation',
            'battery': 'Batterie',
            'type': 'Type de Carte SIM',
            'camera_front': 'Camera Frontale',
            'camera_rear': 'Camera Arriere',
            'video': 'Resolution de la video',
            'category': 'Categorie',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'rom': forms.NumberInput(attrs={'class': 'form-control'}),
            'ram': forms.NumberInput(attrs={'class': 'form-control'}),
            'cpu': forms.TextInput(attrs={'class': 'form-control'}),
            'taille': forms.NumberInput(attrs={'class': 'form-control'}),
            'resolution': forms.TextInput(attrs={'class': 'form-control'}),
            'profndeur': forms.NumberInput(attrs={'class': 'form-control'}),
            'Rafra': forms.NumberInput(attrs={'class': 'form-control'}),
            'system': forms.TextInput(attrs={'class': 'form-control'}),
            'battery': forms.NumberInput(attrs={'class': 'form-control'}),
            'type': forms.TextInput(attrs={'class': 'form-control'}),
            'camera_front': forms.NumberInput(attrs={'class': 'form-control'}),
            'camera_rear': forms.NumberInput(attrs={'class': 'form-control'}),
            'video': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

        error_messages = {
            'title': {
                'required': 'Le titre est obligatoire',
                'max_length': 'Le titre ne doit pas dépasser 100 caractères',
                'min_length': 'Le titre doit avoir au moins 3 caractères',
            },
            'price': {
                'required': 'Le prix est obligatoire',
            },
            'rom': {
                'required': 'Le stockage interne est obligatoire',
            },
            'ram': {
                'required': 'La mémoire vive est obligatoire',
            },
            'cpu': {
                'required': 'Le processeur est obligatoire',
            },
            'taille': {
                'required': 'La taille de l\'ecran est obligatoire',
            },
            'resolution': {
                'required': 'La resolution de l\'ecran est obligatoire',
            },
            'profndeur': {
                'required': 'La profondeur de couleur est obligatoire',
            },
            'Rafra': {
                'required': 'Le rafraichissement de l\'ecran est obligatoire',
            },
            'system': {
                'required': 'Le système d\'exploitation est obligatoire',
            },
            'battery': {
                'required': 'La batterie est obligatoire',
            },
            'type': {
                'required': 'Le type de carte SIM est obligatoire',
            },
            'camera_front': {
                'required': 'La camera frontale est obligatoire',
            },
            'camera_rear': {
                'required': 'La camera arriere est obligatoire',
            },
            'video': {
                'required': 'La resolution de la video est obligatoire',
            },
            'category': {
                'required': 'La categorie est obligatoire',
            },
        }

        

class MobileImageForm(forms.ModelForm):
    class Meta:
        model = MobileImage
        fields = ('mobile', 'image')
        labels = {
            'mobile': 'Mobile',
            'image': 'Image',
        }
        widgets = {
            'mobile': forms.Select(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

src/mobile/views.py
from .models import Category, Mobile, MobileImage
from django.views.generic import ListView ,DetailView, CreateView , UpdateView , DeleteView
from .forms import CategoryForm, MobileForm
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from prometheus_client import Summary
from prometheus_client.core import CollectorRegistry

def index (request):
  return render(request, 'index.html')

class CategoryListView(ListView):
    model = Category
    template_name = 'category\category_list.html'
    context_object_name = 'categories'
    ordering = ['id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Categories'
        return context

class CategoryDetailView(DetailView):
    model = Category
    template_name = 'category\category_detail.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mobiles = Mobile.objects.filter(category=self.get_object())
        context['title'] = 'Category'
        context['mobiles'] = mobiles
        return context


class MobileCategoryListView(ListView):
    model = Mobile
    template_name = 'mobile\mobile_list_category.html'
    context_object_name = 'mobiles'
    ordering = ['-id']

    def get_queryset(self):
        return Mobile.objects.filter(category__id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.get(pk=self.kwargs['pk'])
        context['title'] = 'Mobiles'
        context['category'] = category
        return context

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['Admin','SMC','IT']).exists() or u.is_superuser), name='dispatch')
class CategoryCreateView(CreateView):
    model = Category
    template_name = 'category\category_create.html'
    form_class = CategoryForm
    success_url = reverse_lazy('mobile:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create Category'
        return context
   
@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['Admin','SMC','IT']).exists() or u.is_superuser), name='dispatch')
class CategoryUpdateView(UpdateView):
    model = Category
    template_name = 'category\category_update.html'
    form_class = CategoryForm
    success_url = reverse_lazy('mobile:home')
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Category'
        return context

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['Admin','SMC','IT']).exists() or u.is_superuser), name='dispatch')
class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'category\category_delete.html'
    context_object_name = 'category'
    success_url = reverse_lazy('mobile:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete Category'
        return context
    
# Mobile Views

class MobileListView(ListView):
    model = Mobile
    template_name = 'mobile\mobile_list.html'
    context_object_name = 'mobiles'
    ordering = ['-id']
    paginate_by = 1

    def get_context_data(self, **kwargs):
        categories = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mobiles'
        context['categories'] = categories
        
        return context

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['Admin','SMC','IT']).exists() or u.is_superuser), name='dispatch')
class MobileCreateView(CreateView):
    model = Mobile
    template_name = 'mobile\mobile_create.html'

    form_class = MobileForm
    success_url = reverse_lazy('mobile:mobile_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.all()
        context['title'] = 'Create Mobile'
        context['category'] = category
        return context
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            image = request.FILES.get('image')
            image1 = request.FILES.get('image1')
            image2 = request.FILES.get('image2')     
            mobile = Mobile.objects.last()
            MobileImage.objects.create(mobile=mobile, image=image)
            MobileImage.objects.create(mobile=mobile, image=image1)
            MobileImage.objects.create(mobile=mobile, image=image2)
            Category.objects.get(id=request.POST.get('category')).mobiles.add(mobile)
            return redirect('mobile:mobile_list')
        else:
            return render(request, self.template_name, {'form':form })

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['Admin','SMC','IT']).exists() or u.is_superuser), name='dispatch')
class MobileUpdateView(UpdateView):
    model = Mobile
    template_name = 'mobile\mobile_update.html'
    form_class = MobileForm
    success_url = reverse_lazy('mobile:mobile_list')
   

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Mobile'
        return context

@method_decorator(user_passes_test(lambda u: u.groups.filter(name__in =['Admin','SMC','IT']).exists() or u.is_superuser), name='dispatch')
class  MobileDeleteView(DeleteView):
    model = Mobile
    template_name = 'mobile\mobile_delete.html'
    context_object_name = 'mobile'
    success_url = reverse_lazy('mobile:mobile_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete Mobile'
        return context
    
class MobileDetailView(DetailView):
    model = Mobile
    template_name = 'mobile\mobile_detail.html'
    context_object_name = 'mobile'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        images = MobileImage.objects.filter(mobile=self.object)
        category = Mobile.objects.get(id=self.object.id)
        context['images'] = images
        context['title'] = 'Mobile'
        context['category'] = category
        return context

src/mobile/templates/category/category_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section   style="margin-top: 2cm;">
    <div style="background-color: orangered; border-radius: 20px; padding: 10px;"
    class="container py-5 h-100" >
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <div class="card rounded-3">
                    <img src="{% static 'img/bgcat.jpg' %}" class="w-80" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;
                        height: 300px;"
                        alt="Sample photo">
                    <div class="card-body p-2 p-md-5">
                        <h3 class="mb-2 pb-2 pb-md-0 mb-md-2 px-md-2 text-center" style="color: orangered;" >Créer une nouvelle catégorie</h3>
                        <form method="post" >
                            {% csrf_token %}
                            <div class="form-outline mb-2">
                                <input type="text" id="{{form.title.id_for_label}}" class="form-control form-control-lg"
                                    name="{{form.title.html_name}}" />
                                <label class="form-label" for="form3Example1q">{{form.title.label}}</label>
                            </div>
                            <div class="form-outline mb-2">
                                <textarea class="form-control" id="{{form.description.id_for_label}}"
                                    rows="4" name="{{form.description.html_name}}"></textarea>
                                <label class="form-label" for="form3Example3q">{{form.description.label}}</label>
                            </div>
                            <button type="submit" class="btn black btn-lg btn-block mb-1" style="color: white; background-color: orangered;">Créer</button>
                            <a href="{% url 'mobile:index'%}" class="btn btn-black black btn-lg btn-block mb-1" style="color: white;">Annuler</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

src/mobile/templates/category/category_delete.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 2cm;">
    <h1 style="color: orangered;">Supprimer un Catégorie</h1>
        <form method="post">
        {% csrf_token %}
        <p class="text-black mx-2" >Êtes-vous sûr de vouloir supprimer  {{ category.title }} ?</p>
        <button type="submit" class="btn btn-black">Oui</button>
        <a href="{% url 'mobile:home' %}" class="btn btn-black">Non</a>
    </form>
</div>
{% endblock %}

src/mobile/templates/category/category_detail.html
{% extends 'base.html' %}


{% block content %}
<div style="margin-top: 2cm;">
        <h1 style="color: orangered;" > {{ category.title }} </h1>
    <ul>
            <ol class="list-group list-group-light list-group-numbered">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">{{ category.title}}</div>
                    {{ category.description }}<br>
                    <a style="color: orangered;" href="{% url 'mobile:home' %}">Retour à list des catégories</a>
                  </div>
                  <span class="badge rounded-pill"
                  style="color: orangered; background-color: #f8f9fa; border: 1px solid orangered; font-size: 15px; font-weight: 500;">
                    {{ category.posts|length }}
                  </span>
                </li>                
            </ol>
            <div class="row">
              <div class="col-2 mx-2">
                <a href="{% url 'mobile:category_update' category.pk %}" class="btn btn-black btn-sm btn-block ">Modifier</a>
              </div>
              <div class="col-2">
                <a href="{% url 'mobile:category_delete' category.pk %}" class="btn btn-block btn-sm " style="background-color: orangered; color: white;">Supprimer</a>
              </div>
    </ul>
    <div class="row">
      {% for mobile in mobiles %}
      <div class="col-6 col-md-4 col-lg-3 mb-4">
        <div class="card">
          <div class="d-flex justify-content-between p-3">
            <p class="mb-0"><strong>{{ mobile.title }}</strong></p>
            <div class=" rounded-circle d-flex align-items-center justify-content-center shadow-1-strong" style="width: 35px; height: 35px; background-color: orangered;">
              <p class="text-white mb-0 small text-center">{{ mobile.taille }}</p>
            </div>
          </div>
          {% with mobile.images.first as mobile_image %}
              {% if mobile_image %}
                <img src="{{ mobile_image.image.url }}" class="card-img-top" alt="Mobile Image" 
                style="width: 70%; height: 60%; margin-left:15%;">
              {% else %}
                <p>Pas d'image disponible</p>
              {% endif %}
            {% endwith %}
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <p class="small">
                <a href="#!" class="text-muted">{{ mobile.category }}</a>
              </p>
              <p class="small text-danger">
                <s>{{ mobile.price }}</s>
              </p>
            </div>
            <div class="d-flex justify-content-between mb-3">
              <h5 class="mb-1">{{ mobile.title }}</h5>
              <h5 class="text-dark mb-5"><strong>{{ mobile.price }}</strong></h5>
            </div>
          </div>
          <a href="{% url 'mobile:mobile_detail' mobile.id %}" class="btn btn-primary " style="border-radius: 0.25rem 0.25rem 0.25rem 0.25rem; background-color: orangered; border-color: orangered;">View Details</a>
          {% if user.groups.all.0.name == 'IT' or user.is_superuser or user.groups.all.0.name == 'SMC' %}
          <a href="{% url 'mobile:mobile_update' mobile.id %}" class="btn btn-warning mt-2 bold" style="border-radius: 0.25rem 0.25rem 0.25rem 0.25rem; background-color: black; border-color: black;">Modifier le mobile</a>
          <a href="{% url 'mobile:mobile_delete' mobile.id %}" class="btn btn-danger mt-2" style="border-radius: 0.25rem 0.25rem 0.25rem 0.25rem; background-color: white; color: black; ">Supprimer le mobile</a>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

src/mobile/templates/category/category_list.html
{% extends 'base.html' %}


{% block content %}
<div style="margin-top: 2cm;">

  <div class="row">
    <div class="col-md-6">
      <div class=" d-flex align-items-center">
        <a href="{% url 'mobile:index' %}"><i class="fas fa-arrow-left fa-2x mx-2" style="color: orangered;"></i></a>
        <h1 class="text-black text-bold">Liste des catégories</h1>
      </div>
    </div>
    <div class="col-md-2 ms-auto mt-3 ">
      <a href="{% url 'mobile:category_create' %}" class="btn  btn-sm content-center " style="background-color: black; color: white;">Ajouter une catégorie</a>
    </div>
    <hr>
  </div>
    <ul>
        {% for category in categories %}
            <ol class="list-group list-group-light ">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">{{ category.title}}</div>
                    {{ category.description|truncatechars:150 }}
                    <a style="color: orangered;" href="{% url 'mobile:category_detail' category.pk %}">Voir plus</a>
                  </div>
                  <span class="badge rounded-pill"
                  style="color: orangered; background-color: #f8f9fa; border: 1px solid orangered; font-size: 15px; font-weight: 500;">
                    {{ category.id }}
                  </span>
                </li>    
                <div class="row">
                  <div class="col-2 mx-2">
                    <a href="{% url 'mobile:category_update' category.pk %}" class="btn btn-black btn-block btn-sm">Modifier</a>
                  </div>
                  <div class="col-2">
                    <a href="{% url 'mobile:category_delete' category.pk %}" class="btn btn-block btn-sm " style="background-color: orangered; color: white;">Supprimer</a>
                  </div>
              </div>
              </ol>
        {% endfor %}
    </ul>
</div>
{% endblock %}

src/mobile/templates/category/category_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section  style="margin-top: 2cm;">
    <div style="background-color: #e27005;" class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <div class="card rounded-3">
                    <img src="{% static 'img/bgcat.jpg' %}" class="w-80" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;
                        height: 300px;"
                        alt="Sample photo">
                    <div class="card-body p-2 p-md-5">
                        <h3 class="mb-2 pb-2 pb-md-0 mb-md-2 px-md-2"
                        style="color: #e27005;" >Modifier un categorie</h3>
                        <form method="post" >
                            {% csrf_token %}
                            <div class="form-outline mb-2">
                                <input type="text" id="{{form.title.id_for_label}}" class="form-control form-control-lg"
                                    name="{{form.title.html_name}}" value="{{form.title.value}}" />
                                <label class="form-label" for="form3Example1q">{{form.title.label}}</label>
                            </div>
                            <div class="form-outline mb-2">
                                <textarea class="form-control" id="{{form.description.id_for_label}}"
                                    rows="6" name="{{form.description.html_name}}">
                                    {{form.description.value}}
                                </textarea>
                                <label class="form-label" for="form3Example3q">{{form.description.label}}</label>
                            </div>
                            <button type="submit" class="btn btn-black black btn-lg btn-block mb-1 mt-2">Modifier</button>
                            <a href="{% url 'mobile:home' %}" class="btn btn-black btn-block" style="background-color: #e27005;">Annuler</a>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}